### ISSUE TITLE
Looking For Typos "Preparing Product data"

### ISSUE THREAD

**Issue by lani0016** [lani0016/ecommerce-pattern-library#4]
Hi @thomasjbradley , Please let me know which lines contain the typos as soon as you get the chance.

**Comment by lani0016** [comment]
Hi @thomasjbradley , I have also finished the Jekyll generators  assignment and was wondering if  i may get your help spell checking for this section as well.

**Comment by thomasjbradley** [comment]
Can you do a commit & push please? There hasn’t been a commit since the middle of March.

**Comment by lani0016** [comment]
Hi @thomasjbradley, I just committed and pushed

**Comment by thomasjbradley** [comment]
Outdent this whole section so it’s touching the side:
https://github.com/lani0016/ecommerce-pattern-library/blob/master/_config.yml#L25-L32

And then there’s some indentation & spacing issues too.

It should look like this:

```yml
collections:
  products:
    output: true
defaults:
  - scope:
      path: _products
    values:
      layout: product
```

**Comment by thomasjbradley** [comment]
Let me know how that works.

**Comment by lani0016** [comment]
@thomasjbradley ,
great! I can see everything except the images, though that might be some fiddling to fix, though the Jekyll generator assignment has worked wonderfully

**Comment by thomasjbradley** [comment]
Can you please commit & push again so I can look at the website?

**Comment by lani0016** [comment]
so sorry for the late reply, I had  my birthday celebrations, but i just committed and pushed again @thomasjbradley

**Comment by lani0016** [comment]
on a side note,  I have everything I need on my homepage up and running

**Comment by thomasjbradley** [comment]
I’ve found some typos in all the product MD files, which is why the images aren’t loading.

1. The text after the `description` needs to be indented
2. The list of colours needs to be indented & have a space after the dash
3. The bottom triple dashes is missing

Here’s a working example:

```yml
---
name: "Hello Softness Kit"
description: |
  Ideal for the most sensitive skin and stomachs, this kit has the most gentle and natural products on the market
image: "/images/hello-softness.jpg"
price: 30
colors:
  - "teal"
  - "light-grey"
shape: "square"
clarity: "VVS1"
---

```

**Comment by lani0016** [comment]
Hi @thomasjbradley , I just wanted to let you know where i'm at with my code. Currently I'm just finishing up the  documentation after having my product list page template, but I am having  a bit of trouble with my descriptions not showing up and I figure it's probably a small issue that I just haven't caught yet.

Otherwise, I feel as though I may be ready for the next lesson which is  the "repo setup and branching" lesson. If I am ready to move forward, I was wondering how I will do this tandem portion of the website since i'm not "in studio".

**Comment by thomasjbradley** [comment]
Yeah, the indentation is a little whacky. Here’s an example from the `buttons/config.yml` file:

These lines should look like the code below:
https://github.com/lani0016/ecommerce-pattern-library/blob/master/_patterns/buttons/config.yml#L5-L15

```yml
patterns:
  basic:
    title: "Basic"
    description: |
      Default to using the basic button. It should always be used in the front of light backgrounds.
    width: "12em"
  ghost:
    title: "Ghost"
    description: |
      The ghost button is specifically for banners, where it will be placed in front of busy images.
    background: "--color-primary-light"
```

The indentation keeps getting deeper, like every pattern is inside the previous pattern.

Also be careful when using the vertical pipe: (`|`) the lines afterwards must always be indented one more level.
